### ISSUE TITLE
Couldn't install pyeq2.

### ISSUE THREAD

**Issue by yiboLi** [zunzun/zunzunsite#1]
Hi there, I was trying to install this site but it got stuck after I run: sudo pip install pyeq2. I use Windows so I build a ubuntu virtual machine to run this software. I first git cloned zunzunsite, then installed all the packages by: sudo apt-get install python-XXX (followed those steps in README.txt), then run: sudo pip install pyeq2, I got the error message as following:

_Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip_build_root/scipy/setup.py", line 265, in <module>
    setup_package()
  File "/tmp/pip_build_root/scipy/setup.py", line 262, in setup_package
    setup(*_metadata)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "/tmp/pip_build_root/scipy/setup.py", line 182, in configuration
    config.add_subpackage('scipy')
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(_args)
  File "scipy/setup.py", line 15, in configuration
    config.add_subpackage('linalg')
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/linalg/setup.py", line 20, in configuration
    raise NotFoundError('no lapack/blas resources found')
numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_root/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-ZnpOIG-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/scipy
Storing debug log for failure in /home/vagrant/.pip/pip.log_

Then I ran server and got nothing. What is going on here?What did I do wrong?
Thanks a lot!

**Comment by zunzun** [comment]
The clue is at the bottom of the error message (thanks!) which shows:

numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

It appears to be a problem with the numpy install.  My suggestion is to try

pip install numpy

and see what happens.

James

**Comment by yiboLi** [comment]
Hi zunzun,
I am sorry to bother you again, I just ran into another issue. After I run "sudo apt-get update && sudo apt-get dist-upgrade", all the packages including pyeq2 are successfully installed. Then I ran server and still got nothing there...
Then I found out that there is a bug when I try to upgrade scipy, so I installed many other packages and installed numpy and scipy again. It seemed everything works fine now, but still I got nothing from server...

**Comment by zunzun** [comment]
Hmm.  Please try the following commands in a Python shell:

import scipy
import pyeq2
import django

and let me know if there are any errors.

James

**Comment by yiboLi** [comment]
They all work just fine.

**Comment by zunzun** [comment]
Very good.

What happens when you run the command

python manage.py runserver

in a terminal?  What should happen is that some text will scroll by, and at the end it should show something like this:

Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

James

**Comment by zunzun** [comment]
If you see the development server start, everything is working.

James
